name: Devfile Registry Maintainer

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  devfile-registry-maintainer:
    runs-on: ubuntu-latest
    name: Maintains registry stacks
    steps:
      - name: Deprecate or Remove expired stacks
        id: deprecate-remove
        uses: thepetk/devfile-registry-maintainer@a4014b57af32c64c50a235da5a3f1c2c2c18fb42 #v0.1.0
        with:
          registry_repo_token: ${{ secrets.REGISTRY_REPO_TOKEN }}
          pr_creation_limit: "2"
          deprecation_days_limit: "200"
          removal_days_limit: "200"
