name: Devfile Registry Maintainer

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  devfile-registry-maintainer:
    runs-on: ubuntu-latest
    name: Maintains registry stacks
    steps:
      - name: Deprecate or Remove expired stacks
        id: deprecate-remove
        uses: thepetk/devfile-registry-maintainer@77c6a20a419518a74b81fa15d86a81f6d07f0442 #v0.1.0
        with:
          pr_creation_limit: "2"
          deprecation_days_limit: "200"
          removal_days_limit: "200"
