name: Devfile Registry Maintainer

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  devfile-registry-maintainer:
    runs-on: ubuntu-latest
    name: Maintains registry stacks
    steps:
      - name: Deprecate or Remove expired stacks
        id: deprecate-remove
        uses: thepetk/devfile-registry-maintainer@c4685000809143c1b957b1e46b0d3e381a743401 #v0.1.0
        with:
          pr_creation_limit: "2"
          deprecation_days_limit: "200"
          removal_days_limit: "200"
