name: Devfile Registry Maintainer

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  devfile-registry-maintainer:
    runs-on: ubuntu-latest
    name: Maintains registry stacks
    steps:
      - name: Deprecate or Remove expired stacks
        id: deprecate-remove
        uses: thepetk/devfile-registry-maintainer@163cdc11e5179e7b19f4e28d6f0be26dc792f91f #v0.1.0
        with:
          registry_repo_token: $secrets.GITHUB_TOKEN
          pr_creation_limit: "2"
          deprecation_days_limit: "200"
          removal_days_limit: "200"
