name: Devfile Registry Maintainer

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  devfile-registry-maintainer:
    runs-on: ubuntu-latest
    name: Maintains registry stacks
    steps:
      - name: Deprecate or Remove expired stacks
        id: deprecate-remove
        uses: thepetk/devfile-registry-maintainer@bc4257e1a606257f9b2e68a282d731e0a37e3d6e #v0.1.0
        with:
          pr_creation_limit: "2"
          deprecation_days_limit: "200"
          removal_days_limit: "200"
